### ISSUE TITLE
Golang has WebAssembly support now,  version 1.11 added wasm support

### ISSUE THREAD

**Issue by renatosans** [wasm-tool/golang#1]

**Comment by xtuc** [comment]
Yes, would you mind sending a PR to update the setup here? and the doc?

**Comment by aaronpowell** [comment]
Seems not to be that simple, things go boom with Go 1.11.4:

```
preprocessFailed to decode custom "name" section @2475058; ignoring (integer representation too long).
 OK
decode(node:15186) UnhandledPromiseRejectionWarning: Error: integer too large
    at Object.decodeUInt32 (/c/_Projects/github/golang/node_modules/@webassemblyjs/leb128/lib/leb.js:288:11)
    at decodeUInt32 (/c/_Projects/github/golang/node_modules/@webassemblyjs/leb128/lib/index.js:46:23)
    at readU32 (/c/_Projects/github/golang/node_modules/@webassemblyjs/wasm-parser/lib/decoder.js:232:34)
    at parseSection (/c/_Projects/github/golang/node_modules/@webassemblyjs/wasm-parser/lib/decoder.js:1273:15)
    at Object.decode (/c/_Projects/github/golang/node_modules/@webassemblyjs/wasm-parser/lib/decoder.js:1638:25)
    at decode (/c/_Projects/github/golang/node_modules/@webassemblyjs/wasm-parser/lib/index.js:248:21)
    at compileSource.then.bin (/c/_Projects/github/golang/loader.js:118:19)
    at process.internalTickCallback (internal/process/next_tick.js:77:7)
(node:15186) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:15186) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

My guess is that the structure of the WASM generated by the Go compiler has changed since the `@webassembly` dependencies were written.

**Comment by xtuc** [comment]
@aaronpowell this looks more to me like an encoding issue. `@webassemblyjs/*` (i'm the author) has its integer decoding passing the spec tests.

Would you mind trying to load the Wasm module into a Node.js instance or could you please send me it?

**Comment by aaronpowell** [comment]
Done:

```
$> GOOS=js GOARCH=wasm go run -exec="$(go env GOROOT)/misc/wasm/go_js_wasm_exec" .
2019/01/16 10:20:33 test
```

It appears to execute the `main` function as expected.

**Comment by xtuc** [comment]
Ok, thanks for the confirmation, it's definetly a bug on our side. Could you please send me your wasm module? You can send it to my email privately.

**Comment by aaronpowell** [comment]
That was the output of running the sample in this git repo.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by xtuc** [comment]
Ok, I'll investigate that. It's most likely something is not up-to-date here.

**Comment by aaronpowell** [comment]
I've tried in another repo (with Go code about as simple as your demo) but updated the dependencies to 1.8.x.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by xtuc** [comment]
I pushed a couple of updates (example was broken for me) and I can produce it.

**Comment by xtuc** [comment]
https://github.com/wasm-tool/golang/commit/914abbe96c33e75a273ef16427685643454a9c62 fixed the issue you're seeing. However, I ran into https://github.com/golang/go/issues/29786 now.

**Comment by xtuc** [comment]
Sorry for the delay here, I'll work on it asap.

**Comment by aaronpowell** [comment]
No problem. I actually built my own because I was wanting to learn more about how WASM works, how Go works and how webpack works: https://github.com/aaronpowell/webpack-golang-wasm-async-loader

I am keen to see this one in action too, it approaches a few things differently to mine.
